title: "Walter Holzwarth"
email: your-email@domain.com
description: "Golfprofessional aus Leidenschaft"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://walter-holzwarth.de"
repository: "walter-holzwarth/walter-holzwarth.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
exclude:
  - Gemfile
  - Gemfile.lock
